stages:
  - install
  - build
  - test

install_python:
  stage: install
  image: ubuntu:latest
  script:
    - |
      #!/bin/bash
# Function to check if Python is installed
      check_python_installed() {
          command -v python3 &>/dev/null
      }

# Install Python if not installed
      install_python() {
          echo "Python is not installed. Installing Python..."
# Detect the OS and use the appropriate package manager
          if [[ -n "$(command -v apt)" ]]; then
              sudo apt update
              sudo apt install -y python3 python3-pip
          elif [[ -n "$(command -v yum)" ]]; then
              sudo yum install -y python3 python3-pip
          elif [[ -n "$(command -v dnf)" ]]; then
              sudo dnf install -y python3 python3-pip
          elif [[ -n "$(command -v brew)" ]]; then
              brew install python
          else
              echo "Unsupported OS. Manual Python installation needed."
              exit 1
          fi
# Confirm Python installation
          if check_python_installed; then
              echo "Python successfully installed!"
          else
              echo "Python installation failed."
              exit 1
          fi
      }
#Check if Python is installed
      if check_python_installed; then
          echo "Python is already installed."
      else
          install_python
      fi
build:
  stage: build
  script:
    - echo "Running build steps..."
test:
  stage: test
  script:
    - echo "Running tests..."
