stages:
  - install
  - build
  - test
variables:
  PYTHON_VERSION: "3.11"

# This stage installs Python if not already installed
install_python:
  stage: install
  image: rhel8/rhel8  # Using RHEL 8 as the base image
  script:
    - |
      echo "Checking if Python is installed..."
      if ! command -v python3 &>/dev/null; then
        echo "Python not found, installing Python $PYTHON_VERSION..."
        
        # For RHEL 8 or later, use dnf
        if [[ -n "$(command -v dnf)" ]]; then
          sudo dnf install -y python3 python3-pip
        # For RHEL 7 or earlier, use yum
        elif [[ -n "$(command -v yum)" ]]; then
          sudo yum install -y python3 python3-pip
        else
          echo "Package manager not found. Manual Python installation required."
          exit 1
        fi
      else
        echo "Python is already installed."
      fi
build:
  stage: build
  script:
    - echo "Building the project..."
    - python3 --version  # Verify Python installation
test:
  stage: test
  script:
    - echo "Running tests..."
    - python3 -m unittest discover
