trigger:
  branches:
    include:
      - feature/funcapp-fhir-service
pool: 
  name: 'OP-Linux'
steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.11'
    addToPath: true
- script: |
    echo "Updating package lists..."
    sudo yum -y update
    
    echo "Installing Python 3..."
    sudo yum -y install python3
    
    echo "Verifying Python installation..."
    python3 --version
    
  displayName: 'Install Python 3 on RHEL'
- script: |
    echo "Setting Python 3 as default"
    sudo alternatives --set python /usr/bin/python3
  displayName: 'Set Python 3 as Default'